### ISSUE TITLE
Could not load file or assembly 'System.Runtime, Version=4.0.0.0, 

### ISSUE THREAD

**Issue by schurliii** [linuxserver/docker-ombi-armhf#1]
Please have a look at this thread in your forum: 
https://forum.linuxserver.io/showthread.php?tid=442

Thank you!

**Comment by j0nnymoe** [comment]
This has been fixed with this PR: https://github.com/linuxserver/docker-ombi-armhf/pull/2 :)

**Comment by schurliii** [comment]
Thanks to you and sparklyballs, I can confirm that the new image is working for me!
